// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 25NMkq6j3WJSA86YLeNnNv
// Component: KhbxIn74_RWo

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import FullWidthSection from "../../FullWidthSection"; // plasmic-import: CmKNratQvH0p/component

import {
  ThemeValue,
  useTheme
} from "../component_library/PlasmicGlobalVariant__Theme"; // plasmic-import: LpyY4FovdLdy/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_component_library_css from "../component_library/plasmic.module.css"; // plasmic-import: Fu9rYAdx7a38e3uUnu1ra/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 25NMkq6j3WJSA86YLeNnNv/projectcss
import sty from "./PlasmicTextBlockWithHeader.module.css"; // plasmic-import: KhbxIn74_RWo/css

createPlasmicElementProxy;

export type PlasmicTextBlockWithHeader__VariantMembers = {};
export type PlasmicTextBlockWithHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicTextBlockWithHeader__VariantsArgs;
export const PlasmicTextBlockWithHeader__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTextBlockWithHeader__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicTextBlockWithHeader__ArgsType;
export const PlasmicTextBlockWithHeader__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicTextBlockWithHeader__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultTextBlockWithHeaderProps {
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function PlasmicTextBlockWithHeader__RenderFunc(props: {
  variants: PlasmicTextBlockWithHeader__VariantsArgs;
  args: PlasmicTextBlockWithHeader__ArgsType;
  overrides: PlasmicTextBlockWithHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_component_library_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [plasmic_component_library_css.global_theme_finpac]: hasVariant(
            globalVariants,
            "theme",
            "finpac"
          )
        }
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <FullWidthSection
            className={classNames(
              "__wab_instance",
              sty.fullWidthSection___4Nkd7
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__rIE)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4JiSr
                )}
              >
                {"Welcome to Financial Pacific Leasing"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eRgk
                )}
              >
                {
                  "Since 1975 we have been a provider of equipment financing services for businesses nationwide. Let us become Your Financing Partner in Equipment Leasing."
                }
              </div>
            </div>
          </FullWidthSection>
        ),
        value: args.children
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTextBlockWithHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTextBlockWithHeader__VariantsArgs;
    args?: PlasmicTextBlockWithHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTextBlockWithHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTextBlockWithHeader__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTextBlockWithHeader__ArgProps,
          internalVariantPropNames: PlasmicTextBlockWithHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTextBlockWithHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTextBlockWithHeader";
  } else {
    func.displayName = `PlasmicTextBlockWithHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicTextBlockWithHeader = Object.assign(
  // Top-level PlasmicTextBlockWithHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTextBlockWithHeader
    internalVariantProps: PlasmicTextBlockWithHeader__VariantProps,
    internalArgProps: PlasmicTextBlockWithHeader__ArgProps
  }
);

export default PlasmicTextBlockWithHeader;
/* prettier-ignore-end */
