// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: Fu9rYAdx7a38e3uUnu1ra
// Component: Ez5C_DI-e_y8

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 0CdGcjBJJJ2u/component

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: LpyY4FovdLdy/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: Fu9rYAdx7a38e3uUnu1ra/projectcss
import sty from "./PlasmicCard.module.css"; // plasmic-import: Ez5C_DI-e_y8/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: UBqKCOeBv1Lc/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: InBie9uiW3NB/icon

createPlasmicElementProxy;

export type PlasmicCard__VariantMembers = {
  noIcon: "noIcon";
  flat: "flat";
  backgroundColor: "offWhite" | "white";
  noButton: "noButton";
};
export type PlasmicCard__VariantsArgs = {
  noIcon?: SingleBooleanChoiceArg<"noIcon">;
  flat?: SingleBooleanChoiceArg<"flat">;
  backgroundColor?: SingleChoiceArg<"offWhite" | "white">;
  noButton?: SingleBooleanChoiceArg<"noButton">;
};
type VariantPropType = keyof PlasmicCard__VariantsArgs;
export const PlasmicCard__VariantProps = new Array<VariantPropType>(
  "noIcon",
  "flat",
  "backgroundColor",
  "noButton"
);

export type PlasmicCard__ArgsType = {
  headerText?: React.ReactNode;
  bodyText?: React.ReactNode;
  button?: React.ReactNode;
  imageUrl?: string;
  cardIcon?: React.ReactNode;
};
type ArgPropType = keyof PlasmicCard__ArgsType;
export const PlasmicCard__ArgProps = new Array<ArgPropType>(
  "headerText",
  "bodyText",
  "button",
  "imageUrl",
  "cardIcon"
);

export type PlasmicCard__OverridesType = {
  root?: Flex__<"div">;
  h3?: Flex__<"h3">;
};

export interface DefaultCardProps {
  headerText?: React.ReactNode;
  bodyText?: React.ReactNode;
  button?: React.ReactNode;
  imageUrl?: string;
  cardIcon?: React.ReactNode;
  noIcon?: SingleBooleanChoiceArg<"noIcon">;
  flat?: SingleBooleanChoiceArg<"flat">;
  backgroundColor?: SingleChoiceArg<"offWhite" | "white">;
  noButton?: SingleBooleanChoiceArg<"noButton">;
  className?: string;
}

const $$ = {};

function PlasmicCard__RenderFunc(props: {
  variants: PlasmicCard__VariantsArgs;
  args: PlasmicCard__ArgsType;
  overrides: PlasmicCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          imageUrl:
            "https://site-assets.plasmic.app/e025f398a04a33328e1db1bb37e6aeac.svg"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "noIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noIcon
      },
      {
        path: "flat",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.flat
      },
      {
        path: "backgroundColor",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.backgroundColor
      },
      {
        path: "noButton",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noButton
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [projectcss.global_theme_finpac]: hasVariant(
            globalVariants,
            "theme",
            "finpac"
          ),
          [projectcss.global_theme_umpquaBank]: hasVariant(
            globalVariants,
            "theme",
            "umpquaBank"
          ),
          [sty.rootbackgroundColor_offWhite]: hasVariant(
            $state,
            "backgroundColor",
            "offWhite"
          ),
          [sty.rootbackgroundColor_white]: hasVariant(
            $state,
            "backgroundColor",
            "white"
          ),
          [sty.rootflat]: hasVariant($state, "flat", "flat"),
          [sty.rootnoButton]: hasVariant($state, "noButton", "noButton"),
          [sty.rootnoIcon]: hasVariant($state, "noIcon", "noIcon")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__gFuHh, {
          [sty.freeBoxnoIcon__gFuHhr0FZq]: hasVariant(
            $state,
            "noIcon",
            "noIcon"
          )
        })}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__lKt9K)}
              displayHeight={"74px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"74px"}
              loading={"lazy"}
              src={(() => {
                try {
                  return $props.imageUrl;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return {
                      src: "data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeD0iMCIgeT0iMCIgdmlld0JveD0iMCAwIDY1IDY0LjkiIHhtbDpzcGFjZT0icHJlc2VydmUiPgogIDxwYXRoIGQ9Ik01MC43IDMxLjljMCAxMC4xLTguMiAxOC4zLTE4LjMgMTguM1MxNC4yIDQyIDE0LjIgMzEuOXM4LjItMTguMyAxOC4zLTE4LjMgMTguMiA4LjIgMTguMiAxOC4zeiIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMjIxZjIwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiLz4KICA8cGF0aCBkPSJNMzIuNSAxOS4zdjMuOW0wIDE3LjN2NG01LjctMTkuMmMtMS44LS42LTMuNS0xLjItNS4xLTEuNC04LjktMS0xMCA4LS42IDcuOSA5LjIgMCA4LjMgOC45LS42IDcuOS0xLjctLjItMy4zLS44LTUuMS0xLjQiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzIyMWYyMCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIi8+CiAgPGcgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMjIxZjIwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPgogICAgPHBhdGggZD0iTTM5LjEgNTIuM2MzIDUuMSA5LjYgNi44IDE0LjggMy44Ii8+CiAgICA8cGF0aCBkPSJNNTIgNTlsMy4zLTMuMm0tNC41LS44bDQuNS44IiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiLz4KICA8L2c+CiAgPGcgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMjIxZjIwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPgogICAgPHBhdGggZD0iTTIwIDE0Yy0zLTUuMS05LjYtNi44LTE0LjgtMy44Ii8+CiAgICA8cGF0aCBkPSJNNyA3LjNsLTMuMyAzLjJtNC42LjhsLTQuNi0uOCIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIi8+CiAgPC9nPgogIDxwYXRoIGQ9Ik0yMy4yIDEyLjVjMi44LTEuMyA1LjktMi4xIDkuMy0yLjFDNDQuMyAxMC40IDU0IDIwIDU0IDMxLjljMCA5LjYtNi4zIDE3LjctMTQuOSAyMC40TTIwIDE0LjVjLTcuNSA1LjItMTEuMSAxNC43LTguNCAyMy45IDMuMSAxMC4zIDEzLjIgMTYuNSAyMy42IDE1LjEiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzIyMWYyMCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiLz4KICA8cGF0aCBkPSJNNTcuNiA1LjhMNTAuNCAxMm0tLjctMi4zdjMuMWwzLjItLjRNNi43IDU3bDcuMy02bS43IDIuM3YtMy4xbC0zLjIuNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMjExZjIwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIvPgo8L3N2Zz4K",
                      fullWidth: 150,
                      fullHeight: 150,
                      aspectRatio: 1.001541
                    };
                  }
                  throw e;
                }
              })()}
            />
          ),

          value: args.cardIcon
        })}
      </div>
      <h3
        data-plasmic-name={"h3"}
        data-plasmic-override={overrides.h3}
        className={classNames(projectcss.all, projectcss.h3, sty.h3)}
      >
        {renderPlasmicSlot({
          defaultContents: "Card Header",
          value: args.headerText,
          className: classNames(sty.slotTargetHeaderText)
        })}
      </h3>
      <div className={classNames(projectcss.all, sty.freeBox__sE82E)}>
        {renderPlasmicSlot({
          defaultContents:
            "Curabitur iaculis bibendum mauris nec sodales. Donec convallis eu dolor sodales feugiat. ",
          value: args.bodyText,
          className: classNames(sty.slotTargetBodyText, {
            [sty.slotTargetBodyTextnoIcon]: hasVariant(
              $state,
              "noIcon",
              "noIcon"
            )
          })
        })}
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__wKsrs, {
          [sty.freeBoxnoButton__wKsrsggzq4]: hasVariant(
            $state,
            "noButton",
            "noButton"
          )
        })}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <Button className={classNames("__wab_instance", sty.button__t7ZTv)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xf3CE
                )}
              >
                {"Button"}
              </div>
            </Button>
          ),
          value: args.button
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h3"],
  h3: ["h3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h3: "h3";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCard__VariantsArgs;
    args?: PlasmicCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCard__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCard__ArgProps,
          internalVariantPropNames: PlasmicCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCard";
  } else {
    func.displayName = `PlasmicCard.${nodeName}`;
  }
  return func;
}

export const PlasmicCard = Object.assign(
  // Top-level PlasmicCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),

    // Metadata about props expected for PlasmicCard
    internalVariantProps: PlasmicCard__VariantProps,
    internalArgProps: PlasmicCard__ArgProps
  }
);

export default PlasmicCard;
/* prettier-ignore-end */
