// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicProspectiveThirdPartyOriginators,
  DefaultProspectiveThirdPartyOriginatorsProps
} from "./plasmic/fin_pac/PlasmicProspectiveThirdPartyOriginators";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ProspectiveThirdPartyOriginatorsProps extends Omit<DefaultProspectiveThirdPartyOriginatorsProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultProspectiveThirdPartyOriginatorsProps altogether and have
// total control over the props for your component.
export interface ProspectiveThirdPartyOriginatorsProps
  extends DefaultProspectiveThirdPartyOriginatorsProps {}

function ProspectiveThirdPartyOriginators_(
  props: ProspectiveThirdPartyOriginatorsProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicProspectiveThirdPartyOriginators to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicProspectiveThirdPartyOriginators are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all ProspectiveThirdPartyOriginatorsProps here, but feel free
  // to do whatever works for you.

  return <PlasmicProspectiveThirdPartyOriginators root={{ ref }} {...props} />;
}

const ProspectiveThirdPartyOriginators = React.forwardRef(
  ProspectiveThirdPartyOriginators_
);
export default ProspectiveThirdPartyOriginators;
